name: Build GNU

on:
  push:
    branches:
      - main
  pull_request:


jobs:
  awk:
    strategy:
      matrix:
        build: 
          - host: macos-latest
          - host: ubuntu-latest
          - host: ubuntu-latest
            target: "@toolchains_windows//:windows_x86_64"
            apt: sudo apt-get install mingw-w64
    runs-on: ${{ matrix.build.host }}
    defaults:
      run:
        working-directory: gnu/awk
    steps:
      - uses: actions/checkout@v2
      - uses: bazel-contrib/setup-bazel@0.9.1
        with:
          # Avoid downloading Bazel every time.
          bazelisk-cache: true
          # Store build cache per workflow.
          disk-cache: ${{ github.workflow }}
          # Share repository cache between workflows.
          repository-cache: true
      - run: echo "common --platforms=${{matrix.build.target}}" >> .bazelrc
        if: matrix.build.target
      - run: ${{matrix.build.apt}}
        if: matrix.build.apt
      - run: bazel build @gawk//:gawk
      - run: bazel run @gawk//:gawk -- '{ print $2 }' <<< "hello there :)"

  tar:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    defaults:
        run:
          working-directory: gnu/tar
    steps:
        - uses: actions/checkout@v2
        - uses: bazel-contrib/setup-bazel@0.9.1
          with:
            # Avoid downloading Bazel every time.
            bazelisk-cache: true
            # Store build cache per workflow.
            disk-cache: ${{ github.workflow }}
            # Share repository cache between workflows.
            repository-cache: true
        - run: bazel build @tar//src:tar
        - run: bazel run @tar//src:tar -- --help
        
        